# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
    # You can also specify other tool versions:
    # nodejs: "16"
    # rust: "1.55"
    # golang: "1.17"
  jobs:
    pre_install:
      # Install poetry - https://python-poetry.org/docs/master/#installation
      - curl -sSL https://install.python-poetry.org | python -
      - $HOME/.local/bin/poetry env use python
      - $HOME/.local/bin/poetry install
      - $HOME/.local/bin/poetry show
      - $HOME/.local/bin/poetry env info
      - pip list
      - $HOME/.local/bin/poetry run pip list
      - $HOME/.local/bin/poetry run which python
      - which python
      - /home/docs/checkouts/readthedocs.org/user_builds/scikit-rough/envs/rtd/bin/python -m pip list
      - env


# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

# If using Sphinx, optionally build your docs in additional formats such as PDF
# formats:
#    - pdf

# Optionally declare the Python requirements required to build your docs
# python:
#   install:
#     - method: pip
#       path: .
