name: ci-cd

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-in-project: true
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'
      - name: Install dependencies
        run: poetry sync
      - name: Run check
        run: poe check
      - name: Run tests
        run:
          poe testcov
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          # or
          # api-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: coverage-report.xml
      - name: Build documentation
        run: poetry run make -C docs html

  # cd:
  #   needs: ci
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0
  #     - name: Setup Python
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: 3.9
  #     - name: Install Poetry
  #       uses: snok/install-poetry@v1
  #       with:
  #         version: latest
  #         virtualenvs-in-project: true
  #     - name: Python Semantic Release
  #       run: |
  #         pip install python-semantic-release
  #         git config user.name github-actions
  #         git config user.email github-actions@github.com
  #         semantic-release publish
  #     - name: Test publishing package to Test PyPI
  #       uses: pypa/gh-action-pypi-publish@release/v1
  #       with:
  #         user: __token__
  #         password: ${{ secrets.TEST_PYPI_API_TOKEN }}
  #         repository_url: https://test.pypi.org/legacy/
  #     - name: Test install from TestPyPI
  #       run: |
  #         pip install \
  #         --index-url https://test.pypi.org/simple/ \
  #         --extra-index-url https://pypi.org/simple \
  #         skrough
